version: "3.7"
services:
  samba:
    build:
      dockerfile: Dockerfile
      context: ./samba
    network_mode: "host"
    # environment:
      # - CUSTOM_SMB_CONF=false
      # - CUSTOM_USER=false
      # - LOG_LEVEL=info
      # - EXTERNAL_CONF=
      # - HIDE_SHARES=no
      # - MIMIC_MODEL=TimeCapsule8,119
      # - TM_USER=timemachine
      # - TM_GROUPNAME=timemachine
      # - TM_UID=1000
      # - TM_GID=1000
      # - PASSWORD=plasticjesus
      # - SET_PERMISSIONS=false
      # - SHARE_NAME=TimeMachine
      # - SMB_PORT=445
      # - VOLUME_SIZE_LIMIT=0
      # - WORKGROUP=WORKGROUP
    restart: unless-stopped
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    volumes:
     - /tank:/srv/shares
     # - /var/lib/samba:/var/lib/samba
     # - /var/cache/samba:/var/cache/samba
     # - /ect/samba:/etc/samba
     # - /run/samba:/run/samba
    container_name: timemachine
    image: revotus/timemachine
  avahi:
    build:
      dockerfile: Dockerfile
      context: ./avahi
    network_mode: "host"
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
