#!/usr/bin/env bash

DOCKER_REPO=revotus:samba

file="${1:-users.yml}"
cmd=$(which yq)


[ $cmd ] || sudo snap install yq

users=( $(eval "$cmd read $file 'users.(*.groups[*]==shares).*.name'") )

for user in "${users[@]}"; do
    ./create_user_share.sh "${users[@]}"
done