#!/usr/bin/env bash

DOCKER_REPO=revotus:samba

cmd=$(which yq)

[ $cmd ] || snap install yq

users=( $($cmd read 'users.(*.groups[*]==shares).*.name') )
echo $users

# ../create_user_share.sh "${users[@]}"